print(5+3)
a=5
b=2
print(a+b)
a=4
b=6
c=a+b
print(c)
#run time input()
a=int(input("enter the a value"))
b=int(input("enter the b value"))
print(a+b)
a=float(input("enter the a value"))
b=float(input("enter the b value"))
print(a+b)
a=str(input("enter the a value"))
b=str(input("enter the b value"))
print(a+b)
a=input("enter the a value")
b=input("enter the b value")
print(a+b)
a=complex(input("enter the a value"))
b=complex(input("enter the b value"))
print(a+b)
a=bool(input("enter the a value"))
b=bool(input("enter the b value"))
print(a+b)
a=bool(input("enter the a value"))
b=bool(input("enter the b value"))
c=bool(input("enter the c value"))
print(a+b+c)
fname=str(input("first name"))
lname=input("last name")
print((fname+" "+lname).title())
