fname=str(input("first name"))
lname=input("last name")
print((fname+" "+lname).title())
a=int(input("a value"))
b=int(input("b value"))
option=int(input("choose the option 1.add 2.sub 3.multi"))
print(a+b)
print(a-b)
print(a*b)
a=int(input("a value"))
b=int(input("b value"))
option=int(input('''choose the option
             1.add
             2.sub
             3.multi'''))
print(a+b)
print(a-b)
print(a*b)
a=int(input("a value"))
b=int(input("b value"))
option=input("choose the option add sub multi")
print(a+b)
print(a-b)
print(a*b)
a=int(input())
b=int(input())
print(a+b)
